_HYPERPARAMETER_LEARNING_RATE = 0.001
_HYPERPARAMETER_NUMBER_OF_REPLICAS = 300

_HYPERPARAMETER_NUMBER_OF_NEURONS_LAYER_1 = 480
_HYPERPARAMETER_NUMBER_OF_NEURONS_LAYER_2 = 320
_HYPERPARAMETER_NUMBER_OF_NEURONS_LAYER_3 = 32
_HYPERPARAMETER_NUMBER_OF_NEURONS_LAYER_4 = 32
_HYPERPARAMETER_NUMBER_OF_NEURONS_LAYER_5 = 4

_HYPERPARAMETER_NUMBER_OF_EPOCHS = 1000
_HYPERPARAMETER_BATCH_SIZE = 16

_HYPERPARAMETER_LR_PATIENCE = 400
_HYPERPARAMETER_LR_FACTOR = 0.9

_HYPERPARAMETER_EARLYSTOP_PATIENCE_INTEGER = 1000

_DNN_VERBOSE_SETTING = 2